# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Gender',
            new_name='gender',
        ),
    ]
